In [2]:
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

print("Libraries imported successfully.")

Libraries imported successfully.

In [3]:
BASE_DIR = Path.cwd().parent if Path.cwd().name == "notebooks" else Path.cwd()

RAW_DATA_DIR = BASE_DIR / "data" / "raw"
PROCESSED_DATA_DIR = BASE_DIR / "data" / "processed"

print("Base directory:", BASE_DIR)
print("Raw data directory:", RAW_DATA_DIR)
print("Processed data directory:", PROCESSED_DATA_DIR)

Base directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends
Raw data directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends\data\raw
Processed data directory: c:\Users\Charith\Desktop\My Projects\Global-AI-Data-Science-Skills-and-Salary-Trends\data\processed

In [4]:
ai_jobs = pd.read_csv(RAW_DATA_DIR / "ai_jobs.csv")
country_trends = pd.read_csv(RAW_DATA_DIR / "country_ai_trends.csv")
skills_demand = pd.read_csv(RAW_DATA_DIR / "skills_demand.csv")
job_mapping = pd.read_csv(RAW_DATA_DIR / "job_title_mapping.csv")
data_dictionary = pd.read_csv(RAW_DATA_DIR / "data_dictionary.csv")

print("CSV files loaded successfully")

CSV files loaded successfully

In [5]:
print("ai_jobs:", ai_jobs.shape)
print("country_trends:", country_trends.shape)
print("skills_demand:", skills_demand.shape)
print("job_mapping:", job_mapping.shape)
print("data_dictionary:", data_dictionary.shape)

ai_jobs: (50000, 14)
country_trends: (42, 6)
skills_demand: (224605, 4)
job_mapping: (6, 3)
data_dictionary: (13, 3)

In [6]:
print("ai_jobs columns:")
print(ai_jobs.columns.tolist())

print("\ncountry_trends columns:")
print(country_trends.columns.tolist())

print("\nskills_demand columns:")
print(skills_demand.columns.tolist())

print("\njob_mapping columns:")
print(job_mapping.columns.tolist())

print("\ndata_dictionary columns:")
print(data_dictionary.columns.tolist())

ai_jobs columns:
['job_id', 'job_title', 'company_type', 'industry', 'country', 'city', 'remote_type', 'experience_level', 'min_experience_years', 'salary_min_usd', 'salary_max_usd', 'employment_type', 'posted_year', 'company_size']

country_trends columns:
['country', 'year', 'total_ai_jobs', 'avg_salary_usd', 'remote_percentage', 'top_skill']

skills_demand columns:
['job_id', 'skill', 'skill_category', 'skill_level']

job_mapping columns:
['job_title', 'standardized_title', 'role_category']

data_dictionary columns:
['file', 'column', 'description']

In [7]:
ai_jobs.head()

,job_id,job_title,company_type,industry,country,city,remote_type,experience_level,min_experience_years,salary_min_usd,salary_max_usd,employment_type,posted_year,company_size
0,0IFD0TVBDIVU,MLOps Engineer,Research Lab,Education,Australia,Remote,Remote,Entry,0,56873,72223,Full-time,2023,Large
1,ZMF8MDD4V30T,Data Analyst,Startup,Education,Germany,Remote,Remote,Entry,0,54803,85599,Full-time,2024,Medium
2,CX1945NQ4FMY,MLOps Engineer,Research Lab,Tech,Canada,Remote,Remote,Senior,5,149980,175806,Full-time,2021,Large
3,QJ7YHL1C32OC,Applied Scientist,Research Lab,Healthcare,Australia,Remote,Remote,Entry,0,53483,86477,Full-time,2023,Medium
4,F0T0PVN9ER14,Machine Learning Engineer,Research Lab,Finance,Australia,Sydney,Hybrid,Mid,2,102977,127298,Full-time,2023,Large

In [8]:
skills_demand.head()

         job_id            skill skill_category   skill_level
0  E0IFD0TVBDIV                R    Programming      Advanced
1  E0IFD0TVBDIV  Computer Vision             ML         Basic
2  E0IFD0TVBDIV              NLP             ML  Intermediate
3  E0IFD0TVBDIV              SQL    Programming  Intermediate
4  ZMF8MDD4V30T              NLP             ML      Advanced

In [9]:
country_trends.head()

  country  year  total_ai_jobs  avg_salary_usd  remote_percentage top_skill
0     USA  2020          78050          109581                 81    Python
1     USA  2021           5322          116022                 30    Python
2     USA  2022          55204          157026                 39       GCP
3     USA  2023          42906          139108                 25       GCP
4     USA  2024          18847          103070                 63       AWS